-- =========================================================================
-- DCLM OSUN II — Complete Supabase Database Schema
-- Compatible with anonymous visitor sessions & registered members
-- =========================================================================

-- 1. Users Table
create table if not exists public.users (
  id text primary key,
  first_name text not null,
  last_name text not null,
  phone text unique not null,
  region text not null,
  group_name text not null,
  profile_image text,
  is_admin boolean default false,
  role text default 'member',
  registered_at timestamptz default now()
);

alter table public.users enable row level security;
drop policy if exists "Allow public read access to users" on public.users;
create policy "Allow public read access to users" on public.users for select using (true);
drop policy if exists "Allow all operations to users" on public.users;
create policy "Allow all operations to users" on public.users for all using (true) with check (true);

-- 2. Admin Registration Security Codes
create table if not exists public.admin_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  is_valid boolean default true,
  used_by text,
  used_at timestamptz
);

alter table public.admin_codes enable row level security;
drop policy if exists "Allow public access to admin_codes" on public.admin_codes;
create policy "Allow public access to admin_codes" on public.admin_codes for all using (true) with check (true);

-- 3. Carousel Banners
create table if not exists public.carousel_banners (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  description text,
  created_at timestamptz default now()
);

alter table public.carousel_banners enable row level security;
drop policy if exists "Allow public access to carousel_banners" on public.carousel_banners;
create policy "Allow public access to carousel_banners" on public.carousel_banners for all using (true) with check (true);

-- 4. Live Chat Messages
create table if not exists public.live_chat_messages (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  username text,
  text text not null,
  avatar_url text,
  role text default 'member',
  timestamp timestamptz default now(),
  sender_name text,
  message_text text,
  location text,
  is_admin boolean default false
);

alter table public.live_chat_messages enable row level security;
drop policy if exists "Allow public access to live_chat_messages" on public.live_chat_messages;
create policy "Allow public access to live_chat_messages" on public.live_chat_messages for all using (true) with check (true);

-- 5. Live Emoji Reactions
create table if not exists public.live_reactions (
  id bigint generated by default as identity primary key,
  emoji text not null,
  timestamp timestamptz default now()
);

alter table public.live_reactions enable row level security;
drop policy if exists "Allow public access to live_reactions" on public.live_reactions;
create policy "Allow public access to live_reactions" on public.live_reactions for all using (true) with check (true);

-- 6. Radio Listener Presence
create table if not exists public.radio_presence (
  id uuid primary key default gen_random_uuid(),
  user_id text references public.users(id) on delete cascade,
  last_seen timestamptz default now()
);

alter table public.radio_presence enable row level security;
drop policy if exists "Allow public access to radio_presence" on public.radio_presence;
create policy "Allow public access to radio_presence" on public.radio_presence for all using (true) with check (true);

-- 7. Radio Playlist Tracks (24/7 Virtual Radio)
create table if not exists public.radio_tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  speaker text not null,
  audio_url text not null,
  duration integer not null,
  created_at timestamptz default now()
);

alter table public.radio_tracks enable row level security;
drop policy if exists "Allow public access to radio_tracks" on public.radio_tracks;
create policy "Allow public access to radio_tracks" on public.radio_tracks for all using (true) with check (true);

-- 8. Video Tracks
create table if not exists public.video_tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  speaker text not null,
  video_url text not null,
  created_at timestamptz default now()
);

alter table public.video_tracks enable row level security;
drop policy if exists "Allow public access to video_tracks" on public.video_tracks;
create policy "Allow public access to video_tracks" on public.video_tracks for all using (true) with check (true);

-- 9. Library Study Outlines
create table if not exists public.library_outlines (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamptz default now()
);

alter table public.library_outlines enable row level security;
drop policy if exists "Allow public access to library_outlines" on public.library_outlines;
create policy "Allow public access to library_outlines" on public.library_outlines for all using (true) with check (true);

-- 10. App Settings (Broadcast controls & streaming state)
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  last_updated timestamptz default now(),
  updated_by text
);

alter table public.app_settings enable row level security;
drop policy if exists "Allow public access to app_settings" on public.app_settings;
create policy "Allow public access to app_settings" on public.app_settings for all using (true) with check (true);

-- 11. Workforce Departments
create table if not exists public.workforce_departments (
  id text primary key,
  name text not null,
  icon text,
  color text,
  description text,
  meeting_schedule text,
  leader_name text,
  duties jsonb,
  announcements text
);

alter table public.workforce_departments enable row level security;
drop policy if exists "Allow public access to workforce_departments" on public.workforce_departments;
create policy "Allow public access to workforce_departments" on public.workforce_departments for all using (true) with check (true);

-- 12. Workforce Applications
create table if not exists public.workforce_applications (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete cascade,
  department_id text references public.workforce_departments(id) on delete cascade,
  status text default 'pending',
  submitted_at timestamptz default now()
);

alter table public.workforce_applications enable row level security;
drop policy if exists "Allow public access to workforce_applications" on public.workforce_applications;
create policy "Allow public access to workforce_applications" on public.workforce_applications for all using (true) with check (true);

-- 13. Workforce Department Chat Messages
create table if not exists public.workforce_unit_messages (
  id bigint generated by default as identity primary key,
  department_id text references public.workforce_departments(id) on delete cascade,
  user_id text references public.users(id) on delete set null,
  username text not null,
  text text not null,
  timestamp timestamptz default now()
);

alter table public.workforce_unit_messages enable row level security;
drop policy if exists "Allow public access to workforce_unit_messages" on public.workforce_unit_messages;
create policy "Allow public access to workforce_unit_messages" on public.workforce_unit_messages for all using (true) with check (true);

-- 14. Home Cell Locations
create table if not exists public.cell_locations (
  id text primary key,
  name text not null,
  address text not null,
  leader_name text,
  leader_phone text,
  meeting_schedule text,
  region text,
  latitude double precision,
  longitude double precision
);

alter table public.cell_locations enable row level security;
drop policy if exists "Allow public access to cell_locations" on public.cell_locations;
create policy "Allow public access to cell_locations" on public.cell_locations for all using (true) with check (true);

-- 15. Support Tickets
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  issue_type text not null,
  details text,
  status text default 'open',
  created_at timestamptz default now(),
  replied_by text,
  reply text,
  replied_at timestamptz
);

alter table public.support_tickets enable row level security;
drop policy if exists "Allow public access to support_tickets" on public.support_tickets;
create policy "Allow public access to support_tickets" on public.support_tickets for all using (true) with check (true);

-- 16. Giving Transactions
create table if not exists public.giving_transactions (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  amount numeric not null,
  type text not null,
  status text default 'pending',
  created_at timestamptz default now(),
  category text,
  payment_method text
);

alter table public.giving_transactions enable row level security;
drop policy if exists "Allow public access to giving_transactions" on public.giving_transactions;
create policy "Allow public access to giving_transactions" on public.giving_transactions for all using (true) with check (true);

-- =========================================================================
-- Enable Supabase Realtime
-- =========================================================================
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table 
    public.live_chat_messages, 
    public.live_reactions, 
    public.app_settings, 
    public.radio_presence, 
    public.radio_tracks,
    public.carousel_banners,
    public.cell_locations,
    public.workforce_departments,
    public.workforce_unit_messages;
commit;
