-- =========================================================================
-- DCLM OSUN II — Complete Supabase Database Setup & Seed Script
-- Run this ENTIRE script in the SQL Editor of your NEW Supabase Project.
-- =========================================================================

-- 1. Users Table (Supports anonymous sessions & registered members)
create table if not exists public.users (
  id text primary key,
  first_name text not null,
  last_name text not null,
  phone text unique not null,
  region text not null,
  group_name text not null,
  profile_image text,
  is_admin boolean default false,
  role text default 'member',
  registered_at timestamptz default now()
);

alter table public.users enable row level security;
drop policy if exists "Allow public read access to users" on public.users;
create policy "Allow public read access to users" on public.users for select using (true);
drop policy if exists "Allow all operations to users" on public.users;
create policy "Allow all operations to users" on public.users for all using (true) with check (true);

-- 2. Admin Registration Security Codes
create table if not exists public.admin_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  is_valid boolean default true,
  used_by text,
  used_at timestamptz
);

alter table public.admin_codes enable row level security;
drop policy if exists "Allow public access to admin_codes" on public.admin_codes;
create policy "Allow public access to admin_codes" on public.admin_codes for all using (true) with check (true);

-- 3. Carousel Banners
create table if not exists public.carousel_banners (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  description text,
  created_at timestamptz default now()
);

alter table public.carousel_banners enable row level security;
drop policy if exists "Allow public access to carousel_banners" on public.carousel_banners;
create policy "Allow public access to carousel_banners" on public.carousel_banners for all using (true) with check (true);

-- 4. Live Chat Messages
create table if not exists public.live_chat_messages (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  username text,
  text text not null,
  avatar_url text,
  role text default 'member',
  timestamp timestamptz default now(),
  sender_name text,
  message_text text,
  location text,
  is_admin boolean default false
);

alter table public.live_chat_messages enable row level security;
drop policy if exists "Allow public access to live_chat_messages" on public.live_chat_messages;
create policy "Allow public access to live_chat_messages" on public.live_chat_messages for all using (true) with check (true);

-- 5. Live Emoji Reactions
create table if not exists public.live_reactions (
  id bigint generated by default as identity primary key,
  emoji text not null,
  timestamp timestamptz default now()
);

alter table public.live_reactions enable row level security;
drop policy if exists "Allow public access to live_reactions" on public.live_reactions;
create policy "Allow public access to live_reactions" on public.live_reactions for all using (true) with check (true);

-- 6. Radio Listener Presence
create table if not exists public.radio_presence (
  id uuid primary key default gen_random_uuid(),
  user_id text references public.users(id) on delete cascade,
  last_seen timestamptz default now()
);

alter table public.radio_presence enable row level security;
drop policy if exists "Allow public access to radio_presence" on public.radio_presence;
create policy "Allow public access to radio_presence" on public.radio_presence for all using (true) with check (true);

-- 7. Radio Playlist Tracks (24/7 Virtual Radio)
create table if not exists public.radio_tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  speaker text not null,
  audio_url text not null,
  duration integer not null,
  created_at timestamptz default now()
);

alter table public.radio_tracks enable row level security;
drop policy if exists "Allow public access to radio_tracks" on public.radio_tracks;
create policy "Allow public access to radio_tracks" on public.radio_tracks for all using (true) with check (true);

-- 8. Video Tracks
create table if not exists public.video_tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  speaker text not null,
  video_url text not null,
  created_at timestamptz default now()
);

alter table public.video_tracks enable row level security;
drop policy if exists "Allow public access to video_tracks" on public.video_tracks;
create policy "Allow public access to video_tracks" on public.video_tracks for all using (true) with check (true);

-- 9. Library Study Outlines
create table if not exists public.library_outlines (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamptz default now()
);

alter table public.library_outlines enable row level security;
drop policy if exists "Allow public access to library_outlines" on public.library_outlines;
create policy "Allow public access to library_outlines" on public.library_outlines for all using (true) with check (true);

-- 10. App Settings (Broadcast controls & streaming state)
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  last_updated timestamptz default now(),
  updated_by text
);

alter table public.app_settings enable row level security;
drop policy if exists "Allow public access to app_settings" on public.app_settings;
create policy "Allow public access to app_settings" on public.app_settings for all using (true) with check (true);

-- 11. Workforce Departments
create table if not exists public.workforce_departments (
  id text primary key,
  name text not null,
  icon text,
  color text,
  description text,
  meeting_schedule text,
  leader_name text,
  duties jsonb,
  announcements text
);

alter table public.workforce_departments enable row level security;
drop policy if exists "Allow public access to workforce_departments" on public.workforce_departments;
create policy "Allow public access to workforce_departments" on public.workforce_departments for all using (true) with check (true);

-- 12. Workforce Applications
create table if not exists public.workforce_applications (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete cascade,
  department_id text references public.workforce_departments(id) on delete cascade,
  status text default 'pending',
  submitted_at timestamptz default now()
);

alter table public.workforce_applications enable row level security;
drop policy if exists "Allow public access to workforce_applications" on public.workforce_applications;
create policy "Allow public access to workforce_applications" on public.workforce_applications for all using (true) with check (true);

-- 13. Workforce Department Chat Messages
create table if not exists public.workforce_unit_messages (
  id bigint generated by default as identity primary key,
  department_id text references public.workforce_departments(id) on delete cascade,
  user_id text references public.users(id) on delete set null,
  username text not null,
  text text not null,
  timestamp timestamptz default now()
);

alter table public.workforce_unit_messages enable row level security;
drop policy if exists "Allow public access to workforce_unit_messages" on public.workforce_unit_messages;
create policy "Allow public access to workforce_unit_messages" on public.workforce_unit_messages for all using (true) with check (true);

-- 14. Home Cell Locations
create table if not exists public.cell_locations (
  id text primary key,
  name text not null,
  address text not null,
  leader_name text,
  leader_phone text,
  meeting_schedule text,
  region text,
  latitude double precision,
  longitude double precision
);

alter table public.cell_locations enable row level security;
drop policy if exists "Allow public access to cell_locations" on public.cell_locations;
create policy "Allow public access to cell_locations" on public.cell_locations for all using (true) with check (true);

-- 15. Support Tickets
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  issue_type text not null,
  details text,
  status text default 'open',
  created_at timestamptz default now(),
  replied_by text,
  reply text,
  replied_at timestamptz
);

alter table public.support_tickets enable row level security;
drop policy if exists "Allow public access to support_tickets" on public.support_tickets;
create policy "Allow public access to support_tickets" on public.support_tickets for all using (true) with check (true);

-- 16. Giving Transactions
create table if not exists public.giving_transactions (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  amount numeric not null,
  type text not null,
  status text default 'pending',
  created_at timestamptz default now(),
  category text,
  payment_method text
);

alter table public.giving_transactions enable row level security;
drop policy if exists "Allow public access to giving_transactions" on public.giving_transactions;
create policy "Allow public access to giving_transactions" on public.giving_transactions for all using (true) with check (true);

-- =========================================================================
-- Enable Supabase Realtime for Live Chat, Reactions, Settings, Presence
-- =========================================================================
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table 
    public.live_chat_messages, 
    public.live_reactions, 
    public.app_settings, 
    public.radio_presence, 
    public.radio_tracks,
    public.carousel_banners,
    public.cell_locations,
    public.workforce_departments,
    public.workforce_unit_messages;
commit;

-- =========================================================================
-- Seed Initial Default Data (Safe upserts / ON CONFLICT DO NOTHING)
-- =========================================================================

-- Initial Security Admin Registration Codes
insert into public.admin_codes (code, is_valid)
values 
  ('DCLM-ADMIN-2026', true),
  ('OSUN2-ADMIN-PASS', true)
on conflict (code) do nothing;

-- Default App Settings for Radio and Video Streaming
insert into public.app_settings (key, value)
values
  ('radio_broadcast', '{"isLive": false, "streamUrl": "", "streamTitle": "DCLM Virtual Radio 24/7", "currentTrack": "Virtual Radio Feed", "onlineListeners": 0}'::jsonb),
  ('live_broadcast', '{"isLive": false, "streamUrl": "", "title": "DCLM Osun II Live Service", "speaker": "Pastor W.F. Kumuyi"}'::jsonb)
on conflict (key) do update set value = excluded.value;

-- Initial 24/7 Virtual Radio Playlist Tracks
insert into public.radio_tracks (title, speaker, audio_url, duration)
values
  ('THINGS ARE NOT THE SAME ANYMORE', 'DLSO CHOIR', '/audio/radio_track_2.mp3', 660),
  ('THATS ENOUGH', 'DLCF CHOIR', '/audio/radio_track_3.mp3', 368);

-- Default Workforce Departments
insert into public.workforce_departments (id, name, icon, color, description, meeting_schedule, leader_name, duties, announcements)
values
  (
    'dept_media',
    'Media & Technical',
    'fa-video',
    'linear-gradient(135deg, #3b82f6, #1d4ed8)',
    'Livestream, video projection, camera feeds, sound reinforcement.',
    'Saturdays @ 4:00 PM',
    'Brother Isaac Williams',
    '["Manage livestream broadcasting during Sunday Worship and Crusades.", "Coordinate sound system balancing and amplifier settings.", "Execute video coverage, angles, camera panning, and screen projection.", "Setup and tear down media instruments for outreach rallies."]'::jsonb,
    'Special media workshop holds this Saturday at 2:00 PM in the technical booth. All media workers must attend.'
  ),
  (
    'dept_choir',
    'Choir & Orchestral Music',
    'fa-music',
    'linear-gradient(135deg, #ec4899, #be185d)',
    'Singing, anthems, orchestra rehearsals, and special music presentations.',
    'Fridays @ 5:00 PM & Saturdays @ 3:00 PM',
    'Sister Helen Johnson',
    '["Attend weekly voice training and choir rehearsals faithfully.", "Minister in song during Sunday services, Bible study, and special revival meetings.", "Maintain the orderliness and proper care of choir robes and orchestral instruments.", "Assist in writing and arranging sheet music for Sunday specials."]'::jsonb,
    'Rehearsal for the upcoming State Crusade begins this Friday.'
  ),
  (
    'dept_ushering',
    'Ushering & Protocol',
    'fa-user-tie',
    'linear-gradient(135deg, #10b981, #047857)',
    'Welcoming guests, auditorium seating arrangement, and sanctuary orderliness.',
    'Saturdays @ 5:00 PM',
    'Brother John Adeleke',
    '["Warmly receive congregants and guide worshippers to seats.", "Distribute bulletin programs, hymn sheets, and offering envelopes.", "Maintain reverence and smooth movement during altar calls and ministry time."]'::jsonb,
    'All ushers are requested to arrive 45 minutes prior to Sunday Worship.'
  ),
  (
    'dept_security',
    'Sanctuary Security & Traffic',
    'fa-shield-halved',
    'linear-gradient(135deg, #f59e0b, #b45309)',
    'Premises safety, vehicular parking management, and security surveillance.',
    'Sundays @ 7:00 AM',
    'Brother Samuel Ojo',
    '["Coordinate vehicle parking and pedestrian flow in church premises.", "Ensure security of property and safety of congregants throughout church services."]'::jsonb,
    'Security briefing holds every first Sunday of the month.'
  ),
  (
    'dept_children',
    'Children & Youth Ministry',
    'fa-children',
    'linear-gradient(135deg, #8b5cf6, #6d28d9)',
    'Teaching, discipling, and mentoring children and teenagers.',
    'Saturdays @ 3:00 PM',
    'Sister Mary Adeleke',
    '["Prepare engaging Sunday school lessons for children.", "Coordinate scripture recitation and Bible quiz competitions.", "Provide pastoral care and spiritual guidance for young people."]'::jsonb,
    'Children teachers preparation class holds every Saturday at 3:00 PM.'
  )
on conflict (id) do nothing;

-- Default Home Cell Locations
insert into public.cell_locations (id, name, address, leader_name, leader_phone, meeting_schedule, region, latitude, longitude)
values
  ('cell_osogbo_central', 'Osogbo Central Cell', '12 Station Road, Osogbo', 'Pastor David Alabi', '+2348012345678', 'Sundays @ 5:00 PM', 'Osogbo', 7.7827, 4.5418),
  ('cell_ife_central', 'Ile-Ife Main Cell', '5 College Road, Mayfair, Ile-Ife', 'Brother Paul Ogunleye', '+2348023456789', 'Sundays @ 5:00 PM', 'Ile-Ife', 7.4896, 4.5511),
  ('cell_ilesa_central', 'Ilesa Town Cell', '24 Brewery Road, Ilesa', 'Brother Peter Ayodele', '+2348034567890', 'Sundays @ 5:00 PM', 'Ilesa', 7.6294, 4.7417),
  ('cell_ede_central', 'Ede Regional Cell', '8 Polytechnic Road, Ede', 'Pastor Timothy Babatunde', '+2348045678901', 'Sundays @ 5:00 PM', 'Ede', 7.7381, 4.4444)
on conflict (id) do nothing;
